import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { glob } from 'astro/loaders';

// Every .md file in src/content/projects becomes a project page.
// Files starting with "_" (like _template.md) are ignored.
const projects = defineCollection({
  loader: glob({ pattern: '[^_]*.md', base: './src/content/projects' }),
  schema: z.object({
    title: z.string(),
    blurb: z.string(), // one-liner shown on the card
    category: z.enum(['tech', 'finance']), // which Portfolio section it lands in
    group: z.string().optional(), // sub-heading within a category, e.g. "ML growth diary"
    featured: z.boolean().default(false), // also highlighted in the Portfolio "Featured" row
    order: z.number().default(99), // lower = earlier within its section
    tags: z.array(z.string()).default([]),
    repo: z.url().optional(),
    demo: z.url().optional(),
    hero: z.string().optional(), // path under public/, e.g. /images/dcf.png
    wip: z.boolean().default(false), // shows a "work in progress" badge; still visible
    draft: z.boolean().default(false), // true = hidden from the site entirely
  }),
});

// Every .md file in src/content/blog becomes a blog post.
const blog = defineCollection({
  loader: glob({ pattern: '[^_]*.md', base: './src/content/blog' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    date: z.coerce.date(),
    tags: z.array(z.string()).default([]),
    draft: z.boolean().default(false),
  }),
});

// Every .json file in src/content/valuations is a company valuation report,
// generated by the DCF pipeline's exporter (dcf/dcf_report_export.py).
const valuations = defineCollection({
  loader: glob({ pattern: '[^_]*.json', base: './src/content/valuations' }),
  schema: z.object({
    ticker: z.string(),
    company: z.string(),
    as_of: z.string(),
    generated: z.string(),
    currency: z.string(),
    verdict: z.string(),
    confidence: z.string(),
    company_type: z.string(),
    sector: z.string(),
    current_price: z.number(),
    blended_price: z.number(),
    upside_pct: z.number(),
    wacc: z.number(),
    beta_bottom_up: z.number(),
    beta_raw: z.number(),
    models: z.array(z.object({
      approach: z.string(),
      price: z.number(),
      weight: z.number(),
      tv_pct: z.number(),
    })),
    sensitivity: z.object({
      wacc: z.array(z.number()),
      growth: z.array(z.number()),
      prices: z.array(z.array(z.number())),
    }),
    reverse: z.object({
      implied_constant: z.number(),
      implied_fade: z.number(),
      implied_return: z.number(),
      dividend_yield: z.number(),
      buyback_rate: z.number(),
      implied_total_return: z.number(),
      market_percentile: z.number(),
    }),
    triangulation: z.object({
      fwd_year: z.number(),
      implied: z.number().nullable(),
      guidance_rev: z.number().nullable(),
      consensus_rev: z.number().nullable(),
      consensus_rev_low: z.number().nullable(),
      consensus_rev_high: z.number().nullable(),
      consensus_analysts: z.number(),
      consensus_ebitda: z.number().nullable(),
      consensus_eps: z.number().nullable(),
      demonstrated_cagr: z.number().nullable(),
    }).nullable(),
    drivers: z.array(z.string()).default([]),
    flags: z.array(z.string()).default([]),
  }),
});

export const collections = { projects, blog, valuations };
